export const SELECT_CITY="SELECT_CITY";
export const SELECT_SERVICE="SELECT_SERVICE";
export const OPTIONS_HANDLER="OPTIONS_HANDLER";
export const OPTIONSELECT_HANDLER="OPTIONSELECT_HANDLER";

export const CREATE_SERVICE="CREATE_SERVICE";
export const CREATE_SERVICE_ERROR="CREATE_SERVICE_ERROR";
export const UPDATE_SERVICE="UPDATE_SERVICE";
export const UPDATE_SERVICE_ERROR="UPDATE_SERVICE_ERROR";
export const DELETE_SERVICE_SUCCESS="DELETE_SERVICE_SUCCESS";
export const DELETE_SERVICE_ERROR="DELETE_SERVICE_ERROR";

export const GET_SERVICES_INIT="GET_SERVICES_INIT";
export const GET_SERVICES="GET_SERVICES";
export const GET_SERVICE_ERROR="GET_SERVICE_ERROR";


export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_FAIL="LOGIN_FAIL";

export const LOGOUT="LOGOUT";

export const CREATE_USER="CREATE_USER";
export const VERIFY_EMAIL="VERIFY_EMAIL";

export const CREATE_USER_SUCCESS="CREATE_USER_SUCCESS";
export const CREATE_USER_ERROR="CREATE_USER_ERROR";

export const CREATE_WORKER="CREATE_WORKER";
export const CREATE_WORKER_SUCCESS="CREATE_WORKER_SUCCESS";
export const CREATE_WORKER_ERROR="CREATE_WORKER_ERROR";


export const ADD_TO_CART="ADD_TO_CART";
export const ADD_ORDER="ADD_ORDER";
export const SUB_ORDER="DELETE_ORDER";
export const RESET_ORDER="RESET_ORDER";

export const ADD_SERVICE="ADD_SERVICE";

export const ORDER_SUCCESS="ORDER_SUCCESS";
export const ORDER_UNSUCCESS="ORDER_UNSUCCESS";